version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Install phase complete"

  build:
    commands:
      - echo "No build necessary for static site"

  post_build:
    commands:
      - echo "Starting deploy to S3..."
      - aws s3 cp dist/ s3://chamidu-portfolio-site/ --recursive
      - echo "Deploy complete"

artifacts:
  files:
    - '**/*'
